### ISSUE TITLE
Investigate how to redo approach of static pages on the UI

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#169]
Make it easier to change the PASS front page. Have it managed by a CMS like WordPress and then link to the actual application.

**Comment by jabrah** [comment]
## What are the static pages and how are they different from the PASS application?
  
When we refer to the "static pages" in the OA-PASS codebase, we are normally talking about the `pass-ui-static` repository. This repo contains all of the assets that need to be publicly accessible -- assets that can't be kept behind the authentication (shibboleth) wall. These files include some static landing pages, error pages, and some CSS and fonts.

The static pages also contains a JSON configuration file that the Ember application will read in order to know where to retrieve branding assets (CSS files, fonts, etc)

## Why do we need to rework how the static pages are handled?

* Development / modifying static pages is very painful
* Rebranding requires developer resources
  - Need to manually modify several static HTML and CSS files, committing to Github, creating and deploying a new Docker image
* Branded landing page not the point of the PASS project

## Refactoring goals

* IMO it would be nice to keep the current branding capabilities, as it is useful for self-hosted instances of the PASS application
* Allow institutions to define their own landing pages using whatever means they see fit
  - Allow linking to the Eclipse-hosted PASS app, that has neutral (or Eclipse) branding
  - Also lets institutions link to self-hosted app

## Links between the static pages and Ember app

These points will inform any refactoring work that will need to be done

* Ember app looks for a JSON config file (config file location is configured via env var)
* Many error pages are routed to static pages
* Header includes links to static pages (FAQ, about, etc)
* All branding assets are hosted with the static pages, pulled in to the Ember app through the JSON config
* Static pages should have no dependency on Ember app

**Comment by jabrah** [comment]
## Actions 

We'll move anything we need to keep to support the PASS application. Everything else will stay in the current `pass-ui-public` repo, which can later be archived.

* Move all required assets into the PASS app codebase (`pass-ui`)
  - config.json
  - branding assets - CSS, logo, etc
* Modify how configured vars are read: remove the `assetsUri` thing
* Add env vars to enable modifications. PASS application will embed default values for the configs, which can be overridden in a given deployed instance
  - branding assets (logo, CSS, homepage link, etc)
  - error pages
* Update `pass-docker` and `pass-ui` dev environment to remove the `pass-ui-public` component

These changes should not be a huge amount of effort and will maintain the current reskinning capabilities of the PASS application, while removing the extraneous static pages.

Note: the last piece will have an effect on the application deployment, since it would be removing a piece of the PASS stack. The top level proxy may have some dependencies, in that it may point to this server for error pages, will have to investigate.

**Comment by bbranan** [comment]
@jabrah I assume the first action is really to make a *copy* of all required assets and place them in `pass-ui`. We'd want to keep the current set of resources in place within `pass-ui-public` as a reference and for use with the current internal deployment.

Overall this approach looks good to me, but I'd be interested to hear from @jaredgalanis @markpatton @jrmartino if they have any suggestions or concerns.

**Comment by jabrah** [comment]
`copy` is correct - `move` was the wrong term to use in this context.

**Comment by markpatton** [comment]
I like the idea of configuring those urls with environment variables. But those environment variables will be resolved at build time and so will get baked into an image. If we wanted to be able to configure those variables at runtime, we would have to do something like have a configuration file which the application loads on startup. It might be interesting to know if there are any ember best practices for runtime configuration.

**Comment by jabrah** [comment]
As noted on the PR in `pass-docker`: I'm a bit hesitant to merge the changes that removes `static-html` at the moment, since I don't have a good understanding of how we'd handle (i.e. codebase, deployment, etc) the current static pages in the JHU local instances

**Comment by jabrah** [comment]
Tagging @jgara for reference

Since the `static-html` image is currently used in the JHU-hosted instances of PASS, I'd suggest that we re-create the `pass-ui-public` repository, either in the previous `OA-PASS` or `jhu-sheridan-libraries` GH organizations. 

Eventually, I think it would be nice to have a JHU run static website serve as the static pages for the JHU instance, perhaps using WordPress, which is already in use in many places in the library and university. After merging the PR linked in this ticket, we should be able to host and utilize branding assets from this site, similar to our prior setup. This would all but eliminate the need for developer resources when changing things on the static pages.
