### ISSUE TITLE
Stand up an independent instance of PASS using Eclipse infrastructure and mock/demo data

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#178]
The work done here should conclude with a running version of PASS, similar to what is provided in the pass-docker repo. The system should be running on a kubernetes cluster managed by the Eclipse Foundation.

**Comment by aforward** [comment]
We are working on two fronts... "standing _something_ up" versus "standing up a representative system".  These notes are about standing something up (i.e. docker based on docker-compose) and not about the representative system (k8s cluster)

My objective is to get it tied into GH actions, most likely on a nightly schedule so that any new docker images posted to that repo will be auto-deployed each night.  The "nightly" is for now as we figure out the grouping of applications to trigger a "new deploy"

And, I would like to create a different branch (e.g. `nightly`) instead of `minimal-assets

Here's the current URL (note the server is currently OFF so that URL will not do anything)
https://passdev.a4word.com/

<img width="1306" alt="Screen Shot 2022-06-24 at 10 38 05" src="https://user-images.githubusercontent.com/48086/175559574-ec6b71fc-c220-42d1-b330-d61ddd371985.png">


I am looking at the following next steps

1) Setting up the right config variables to the links work (i.e. pass.local => [passdev.a4word.com]

2) Adding a "version number" someone on the page (so that I can test the new versions are actually deployed

3) Working through "updating" the docker images (first manually so we can verify (2) but then possibly automatically... or at least thinking about how to track that)

**Comment by aforward** [comment]
Tracking EF ops work here
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1660

**Comment by aforward** [comment]
The internal infra project for managing the EF servers will be
https://gitlab.eclipse.org/eclipsefdn/it/infra/eclipse-pass

(note that you probably don't have access, it's more to document its location)

I will ensure that the _gist_ of that configuration work is shared back so that others could anisble configure a pass instance.

**Comment by aforward** [comment]
Here are the requirements for an eclipse hosted site
https://www.eclipse.org/org/documents/eclipse-foundation-hosted-services-privacy-and-acceptable-usage-policy.pdf

**Comment by aforward** [comment]
Current status with EF

Thanks for the information.  The PASS team would prefer more control over the editing of the site, and have landed on using GitHub Pages to host the site.

* [ ] New github repo called /eclipse-pass/eclipse-pass.github.io
* [ ] CNAME record * (eclipse-pass.org) that points to eclipse-pass.github.io
* [ ] Custom domain setup (or admin access to) eclipse-pass/eclipse-pass.github.io/settings/pages

I have worked through the above on a sample site visible at (https://eclipse-pass.anunknown.dev) and based on  the process myself (to confirm it is viable) based on (https://github.com/aforward/aforward.github.io).

Here is the documentation that I used
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

And a screenshot of my configuration (from my personal repo on a person domain... this was just for testing the process)

<img width="605" alt="Screen Shot 2022-09-13 at 18 47 51" src="https://user-images.githubusercontent.com/48086/190022784-171f71be-3187-498c-9e91-36ba03a415f8.png">

**Comment by aforward** [comment]
Servers are running docker, pass-docker (code, app is "off" by default) and GH self-hosted server app and I have open tickets with EF to

a) hookup the GH actions to the servers
b) align DNS for demo/nightly.eclipse-pass.org to those setup servers

**Comment by aforward** [comment]
Just waiting on "keys" handshake with EF, but these two PRs when merged should allow us to close down this ticket

https://github.com/eclipse-pass/main/pull/284
https://github.com/eclipse-pass/pass-docker/pull/264

**Comment by aforward** [comment]
EF action runners are setup on pass docker

<img width="357" alt="Screen Shot 2022-09-20 at 11 26 52" src="https://user-images.githubusercontent.com/48086/191299924-8f50f478-4a7f-4c4d-8486-d2f461953ea8.png">


At present they only "docker-compose pull" the data and we are working to make it demo-able
https://github.com/eclipse-pass/main/issues/294

But also working in tandem with the code migration away from fedora to use elide.
