### ISSUE TITLE
Test deployment of PASS in EC2 to validate startup procedures outside of JHU

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#200]
Launch the PASS application in AWS in as simple a manner as possible. This will very likely be tied to JHU data/integration points initially. As those integration points are replaced with mocks/stubs this environment will be an initial testing ground for deploying those changes to ensure they work.

As the Eclipse deployment is built, this environment will provide a reference point. If the application in the Eclipse Kubernetes environment is not working, but it is working in this simplified deployment, that will provide a resource for comparison and analysis.

This deployment is not intended to be used for PASS long-term. It is a stepping point to get us from the JHU environment to the Eclipse environment.

Definition of Done
- A deployment of the latest version of the PASS application is running in AWS
- This deployment can be shut down and brought back up quickly and consistently

**Comment by markpatton** [comment]
- Setup an EC2 instance.
- Make sure instance locked down, not accessible to public.
- Make "public" assets image available
- Attempt to deploy PASS using pass-docker
- Think about security and test users

**Comment by markpatton** [comment]
Created #217 to record fact that pass-docker currently requires docker-compose version 1.

**Comment by markpatton** [comment]
PASS is up and running on https://sandbox.pass.library.jhu.edu. I was able to login as a test user and successfully deposit to the included DSpace.

I created a branch in pass-docker, https://github.com/eclipse-pass/pass-docker/tree/200-test-deployment-of-pass-in-ec2-to-validate-startup-procedures-outside-of-jhu which I used record how the stack was modified. 

I avoided building new images by bind mounting configuration files into the existing images. This was needed for files in httpd-proxy, sp, and idp. See the docker-compose.yml for the changed files. The httpd-proxy had to have certificates overridden because the host was different. The other images just needed changes to environment variables in .env.  A global string replace of pass.local -> sandbox.library.jhu.edu was sufficient.
