### ISSUE TITLE
Make all appropriate PASS repositories children of a parent project

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/main#221]
This issue is to make all code repos children of a parent project, #220. If the parent project contains checkstyle configuration, then each child project will have to be formatted consistently with the style so that it will pass checking.

**Comment by jabrah** [comment]
We can put a check mark on the repos as we start the process of applying the parent POM + checkstyles so that we don't duplicate efforts. Once ready, we can edit this comment to add a link to the PRs we open as part of this ticket

| claimed | repo | PR (when available) |
| :---: | --- | --- |
| <ul><li>[ ] </li></ul> | pass-indexer |  |
| <ul><li>[ ] </li></ul> | pass-java-client |  |
| <ul><li>[ ] </li></ul> | pass-messaging-support |  |
| <ul><li>[ ] </li></ul> | pass-authz |  |
| <ul><li>[ ] </li></ul> | pass-nihms-loader |  |
| <ul><li>[ ] </li></ul> | pass-grant-loader |  |
| <ul><li>[ ] </li></ul> | pass-journal-loader |  |
| <ul><li>[ ] </li></ul> | pass-notification-services |  |
| <ul><li>[ ] </li></ul> | pass-doi-service |  |
| <ul><li>[ ] </li></ul> | pass-package-providers |  |
| <ul><li>[ ] </li></ul> | pass-deposit-services |  |
| <ul><li>[ ] </li></ul> | pass-indexer-checker |  |
| <ul><li>[ ] </li></ul> | pass-fcrepo-jsonld |  |
| <ul><li>[ ] </li></ul> | pass-fcrepo-module-auth-rbacl |  |
| <ul><li>[ ] </li></ul> | pass-fcrepo-jms |  |

**Comment by jrmartino** [comment]
Close #221
