### ISSUE TITLE
Some questions about the overall parent POM

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#230]
We should determine what things to move into the parent POM and some other related issues. Follow-on to https://github.com/eclipse-pass/main/issues/220

* Need to push new parent POM to GitHub Container Registry (Maven Repo) in order to make it generally available to the other stand-alone PASS Java projects.
* Where in eclipse-pass/main should the parent POM live?
  - `eclipse-main/resources/pom.xml` or maybe just at the project's top level `eclipse-main/pom.xml`?
* We should update the various groupIds in all of our various POMS
  - Many currently use `org.dataconservancy.pass` should change to `org.eclipse.pass`
* Parent POM artifactId? `eclipse-pass-parent`; `pass-main`; `pass-parent`? does anyone care?
* Which dependencies should we define in this parent POM? Many of our Java repos use the same dependencies, but many of them use different versions. We'd have to be careful when consolidating these sorts of dependencies (need to make sure all integration tests actually work first)
* Shared properties

**Comment by bbranan** [comment]
My thoughts/questions:
- I see no problem with pushing maven artifacts to GitHub Packages. I see that's already being done with the playground repo. It looks like with prior releases everything had been going to Maven Central (I assume through Sonatype). Making the move to GitHub Packages means that anyone wanting to use PASS maven artifacts will have to add the link to the PASS GitHub Packages maven repo in their pom (which is another step that's not required when using artifacts in central). Anyone want to raise concerns here?
- I'd vote for `eclipse-main/pom.xml`, primarily because it facilitates the common model of stepping into the top level project directory to execute the maven build. It's better if it just works like you'd expect.
- We'll need to ensure the use of `org.eclipse.pass` is acceptable to Eclipse.
- I don't have a strong preference here. Maybe `eclipse-pass-parent`, just for clarity?
- Ideally we'd be moving in the direction of having consistent dependency versions across projects. In fact, I'd like to eventually see the [build fail if there are differing dependency versions](https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html)
  - For now, if there are multiple versions in use, we could include the most current version in the parent pom, then have each project using an older version declare that version in their own pom. This might be easier to manage if dependency versions are defined using properties.
  - I'd suggest including all dependencies defined in the parent pom within `<dependencyManagement>`

Again, just my $0.02 on these questions.

**Comment by aforward** [comment]
I think `org.eclipse-foundation.pass` to avoid confusion with eclipse the application and the open source foundation.

**Comment by markpatton** [comment]
I agree with @bbranan on those answers.

Using dependencyManagement for dependencies to be consistent across the project is important, but may take a while to get sorted out. It could also help us normalize our versioning across projects.  Additionally maven plugin versions should be set with pluginsManagement. It also makes sent to set Java versions as well.

**Comment by jrmartino** [comment]
another wrinkle is that we have some projects which already have a parent pom - spring boot for example

**Comment by bbranan** [comment]
@jrmartino with spring boot there are methods that allow you to use your own parent pom: https://stackoverflow.com/questions/21317006/spring-boot-parent-pom-when-you-already-have-a-parent-pom

**Comment by kineticsquid** [comment]
@bbranan Guidance is to use this mailing list for the questions: https://accounts.eclipse.org/mailing-list/cbi-dev

**Comment by bbranan** [comment]
Question about groupId asked on the recommended Eclipse list: https://www.eclipse.org/lists/cbi-dev/msg02411.html

**Comment by bbranan** [comment]
According to https://www.eclipse.org/projects/handbook/#resources-maven, `org.eclipse.pass` is the expected groupId for the PASS project.

**Comment by bbranan** [comment]
Due to a limitation that was discovered with the with the GitHub Package Registry, the group's determination was to default back to Sonatype/Central. See: https://github.com/eclipse-pass/main/issues/234

**Comment by bbranan** [comment]
Follow-on task to handle dependency updates and dependency convergence checks: https://github.com/eclipse-pass/main/issues/243
