### ISSUE TITLE
Complete Docker image manual builds for 0.1.0 release

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#290]
Manually build and push the fcrepo and pass-indexer Docker images (in that order).

Find instructions under `Docker image release` here: https://github.com/eclipse-pass/main/blob/main/docs/dev/release.md

**Comment by jabrah** [comment]
Published to DockerHub:

* `oapass/fcrepo:0.1.0`
* `oapass/indexer:0.1.0`

Currently trying to run these images through the battery of ITs we have in various projects. @bbranan perhaps doing these tests (and getting them back to functional) is beyond the scope of this ticket (to be saved for #268)?

The documentation says to only publish these two, but my understanding of `pass-docker` is most of these need to be built and published by hand from `pass-docker` in order to get the new tags out. My assumption was that all services should be retagged to an `0.1.0` version

**Comment by jabrah** [comment]
Out of the full list of services in pass-docker: `fcrepo activemq ember static-html ftpserver proxy idp ldap sp dspace pastgres indexer elasticsearch assets deposit authz mail schemaservice policyservice doiservice downloadservice`

---

Only the following have connections to our code repositories: `fcrepo ember static-html indexer deposit authz schemaservice policyservice doiservice downloadservice`. These should be rebuilt.

These have some PASS specific things to them, where they are built out of pass-docker: `activemq ftpserver httpd-proxy idp ldap sp dspace`. **Should these be rebuilt, or simply retagged?**

Two last images are third-party images used pretty much out-of-the-box: `elasticsearch postgres`. These should not be changed for now.

**Comment by bbranan** [comment]
@jabrah I'd suggest rebuilding the full set (besides the last two), just to verify that all changes we've made in moving over to the eclipse-pass baseline are properly captured in the 0.1.0 images.
