### ISSUE TITLE
Investigate use of metadata schema service

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#320]
Look at how the service is actually used by running PASS locally with pass-docker.
See how the service interacts with the PASS data model.
Compare the existing documentation to what is actually happening.
Produce a report with any finding.
Create a pr to fix glaring inconsistencies in the documentation.

**Comment by emmau678** [comment]
Ran the PASS stack locally using docker.
Observed how the service interacts with the PASS data model by investigating activity in the Network tab of Chrome dev tools, following the process of creating a new submission.
Identified inconsistencies within the documentation and created a pull request with suggested changes.
This uncovered another issue relating to references to a previous version of github pages for the repository, which caused tests to fail. That issue is still open at present.

**Comment by markpatton** [comment]
Fixed issue #333 and merged pr.
