### ISSUE TITLE
Implement refactored Java manuscript download service

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#381]
Implementation:
- Service should be fully implemented
- Business logic should separated from HTTP request handling

Documentation:
- The README should be up to date with the implementation
- There should be at least some Javadoc for every class
- Generally public methods should have Javadoc
- Documentation should include build and configuration instructions
- Endpoint documentation should include request and response formats, headers, parameters and response codes
- There should be an example of using each endpoint

Testing:
-There should be unit tests covering the major functionality
- Integration testing will be saved for later

**Comment by jabrah** [comment]
Refactored service brought into the DOI service in pass-core:
https://github.com/eclipse-pass/pass-core/blob/main/pass-core-doi-service/src/main/java/org/eclipse/pass/doi/service/UnpaywallDoiService.java

Unpaywall lookup using DOI was ported, the "download" aspect was not since it was not being used anywhere
