### ISSUE TITLE
Prepare for 0.3.0 release

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#462]
Determine if components ready for release and create release branches to be used.

**Comment by jabrah** [comment]
* [ ] [`main`](https://github.com/eclipse-pass/main) : `0.3.0` already published to Maven Central. `main` branch will be in a good state after https://github.com/eclipse-pass/main/pull/463 is reviewed and merged. Shouldn't need to create a dedicated branch
* [ ] [`pass-core`](https://github.com/eclipse-pass/pass-core) : lots of in-flight work, most of which won't make it into this release
  * [ ] Create `release-0.3.0` branch (instead of `0.3.0` to avoid naming collision with autogenerated release tag from the maven release plugin)
* [ ] [`pass-ui`](https://github.com/eclipse-pass/pass-ui) : difficult to tell if current work will make it into the release
  * [ ] Create `release-0.3.0` branch
* [ ] [`pass-docker`](https://github.com/eclipse-pass/pass-docker) : will need manual attention after all other artifacts are released to update Docker images. Updates:
  * [ ] `pass-core-main` update to latest that will be pushed during release process
  * [ ] `pass-ui` possible image update
  * [ ] `pass-auth`, `proxy`, `pass-ui-public`, `idp`, `ldap` : just need to re-tag current images
* [`pass-support`](https://github.com/eclipse-pass/pass-support) : no work in this repo for this release, safe to release from `main`
* [`pass-auth`](https://github.com/eclipse-pass/pass-auth) : no work since last release
* [`pass-acceptance-testing`](https://github.com/eclipse-pass/pass-acceptance-testing) : no work since last release
