### ISSUE TITLE
Tighten access control of file service

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#489]
Determine what delete and update permissions should be and adjust the service accordingly. Should only creator of a file be able to update and delete?

**Comment by tsande16** [comment]
@markpatton So at the moment, updating a file does not exist. I don't remember the exact details, but IIRC the functionality of updating a file was not needed. The user would only create/read/delete, or the act of updating would be to delete and then recreate the file?

I'm not sure if this functionality was intentionally left out, or if we decided to address it at a later time. I will see if I can find the original conversation or if I have it written down in my notes from a discussion.

**Comment by markpatton** [comment]
We do not need update.

**Comment by tsande16** [comment]
@markpatton I remember you showing us the web security annotations provided by Elide. I revisited what you did just to see if it could be leveraged. Since you understand it much better than me, do you think this could be leveraged for the `FileService` as well, or this is strictly for the `ObjectService` data model? 

I'm not sure if it could be leveraged since it's more role based and to delete it will be tied to a specific user. Also it appears that it would only work on a per class basis? I did want to check with you first to see your thoughts in case you think it could be leveraged for the `FileService`

Example: https://github.com/eclipse-pass/pass-core/blob/main/pass-core-object-service/src/main/java/org/eclipse/pass/object/model/Submission.java
