### ISSUE TITLE
Update Release Automation workflows to deploy a new release to the AWS Pass Demo instance

### ISSUE THREAD

**Issue by cshannon2** [eclipse-pass/main#520]

**Comment by jabrah** [comment]
Temporarily, we can probably update the release workflow of `pass-docker` to include a deploy to AWS. In the standard release procedure, `pass-docker` will be completed last, at which point all necessary docker images will have been created, or will be created within `pass-docker`. Otherwise, there are several issues that need work before we can have a one-release-to-rule-them-all situation
