### ISSUE TITLE
Integrate the data loaders into the staging environment

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#568]
The journal loader, grant loader, and nihms loader should be run periodically.

**Comment by rpoet-jh** [comment]
My initial thoughts on data loader job deployments:

Definitely should run jobs in some kind of server-less environment.  We should avoid using EC2 instances if possible so we don't incur overhead of maintaining the EC2 instance.  Jobs should be packaged as docker containers, then we can look at the different options.

Scheduled ECS Fargate tasks
- Each data loader as docker image
- Push docker images to ERS
- Task definition
- EventBridge cron schedule for starting each data loader task as needed
- Caveat: There is currently no task timeout, so we would need to write something to stop jobs after defined timeout, or add a check in job start to ensure another task doesn't start if job is already running

AWS Batch
- More advanced than we need possibly, but apparently has ability to timeout/not run overlapping jobs
- Runs jobs as Fargate, need docker image and ERS push like ECS
- Need job definition instead of task definition
- Caveat: Job definition can only contain 1 image, ok for now, but may limit.  Using ECS doesn't have this limit and seems simpler.  Also, I have a concern using AWS Batch may be "using a sledgehammer to crack a nut".  However, I will spend some time experimenting with AWS batch to get a better understanding of any complications.

Any data loader jobs that require state in between job runs would have to store data in S3 or AWS EFS volumes.

**Comment by rpoet-jh** [comment]
I spent a few hours experimenting with AWS Batch.  My conclusion is that is seems like a good option for deploying our data loaders.  There is not too much configuration needed in order to run/schedule a batch job.  It also has the needed built in features to support our data loader requirements in a stable way.

Here is the required configuration that I know of now.  There will probably be some additional config discovered when implementing the config, but this should be most of it:

AWS Batch
- Define a Batch compute environment using the Fargate environment (minimal config)
- Define a Batch job queue (minimal config)
- Define a job definition for each data loader.  Most of these will be the same, but we will set data loader docker image URL, appropriate execution timeout values per data loader.
- Configure AWS batch EFS volume that can be used for any files that are needed between batch job runs.  When a Fargate task runs, it gets 20GB of ephemeral disk space.  However, for some data loaders, files are used between batch runs, so persistent disk is needed.  AWS batch EFS does a pretty nice job of automating EFS mount to the Fargate batch job task.

AWS EventBridge
- Create a Rule schedule to run each AWS batch job on appropriate schedule.
- Configure an SNS topic and event rule to receive batch job notifications and send emails for success and failure.

I also propose we use Terraform when configuring the above infrastructure in AWS.  There may be extra time needed to setup our AWS environment to support using terraform, but it would be worth it IMO.

**Comment by rpoet-jh** [comment]
I'm taking no additional comments as all are ok with trying this deployment approach for the data loaders.

I'll put this ticket in Blocked until stage is available.

**Comment by rpoet-jh** [comment]
All data loaders have been configured in stage.  There are a few pending issues related, but they are captured in tickets.

I have created this document describing all AWS resources created for this ticket (plus a few extra things done before this ticket): https://docs.google.com/document/d/12BW2HiY-GeCju2hHRwYeCsgYbYQPOlVZIu-jIxupz-c/edit#heading=h.v3ab2z9s16r2

I completed the configurations using the AWS console.  I'm going to create another ticket to create terraform scripts for the configuration at some point in the, hopefully near, future.
