### ISSUE TITLE
Review prior UX feedback

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#588]
We had prior UX feedback from a JHU UX expert. Much of the feedback was already implemented, but there is some that likely needs addressing / ticketing.

**Comment by jaredgalanis** [comment]
https://docs.google.com/document/d/1ce9lulWajkzcB60UJULXhd72iN0bS_5PAS-tIeplfbk/edit?usp=sharing

**Comment by dkriethof** [comment]
Just to clarify, is the goal of this ticket ("Done") to create specific tickets/tasks for UX changes we plan to make moving forward?

**Comment by dkriethof** [comment]
I organized the feedback into a spreadsheet to track things a little better: https://docs.google.com/spreadsheets/d/1ho71ZCOBLtpjrVg7e7pUbuRTU5DETxBMXj_yzdnPae8/edit?usp=sharing

This way we can move things from To Do to Won't Do, and there is visibility on what was already completed, etc. We should discuss as a team what we want to add as tickets for post 1.0.0 and what we should mark as Won't Do. Also this feedback might be helpful to the PASS Working Group as reference since they will be writing copy/FAQs about the PASS site/workflow.

**Comment by jaredgalanis** [comment]
I think all the items that had links to issues were already done. I think we still need to assess if there is anything that needs to be done. There were some paragraphs with no tickets linked or that were marked explicitly as needs to be done with no closed ticket linked to.

**Comment by dkriethof** [comment]
Yep, my spreadsheet shows the things we did (all tickets linked were closed, as you mentioned). Just need to review the other items and determine next steps for those.
