### ISSUE TITLE
Identify replacement for DSpace deposit

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#612]
The sword2-client library appears to be an inactive github project.  We need to find a replacement.

We should search around for a library that could be used, or investigate using spring WebClient to see it could be used for our needs.

This ticket is to identify and recommend a replacement. Then we can create tickets for implementation.

**Comment by bbranan** [comment]
I reached out to the DSpace tech lead about this, these were his thoughts:

Honestly, I would recommend using the DSpace REST API more at this point, mainly because you have more control (anything you can do from the UI can be done from the REST API in DSpace v7+).  The SWORD 2 Java client is unmaintained right now.  I've reached out to them several times of the last few years, but my understanding is there's literally no one maintaining them.  DSpace recently moved to using the SWORD implementation from GDCC (https://www.gdcc.io/) because it's the only one being semi-maintained: https://github.com/DSpace/DSpace/blob/main/dspace-swordv2/pom.xml#L34-L36

In the end, you can use whatever you want... as DSpace still supports SWORD v2.  But, I share the same concerns about lack of maintenance...so if you want to avoid any risks with using an less maintained client, then go with the DSpace REST API instead.

**Comment by markpatton** [comment]
Consider what versions of DSpace will be supported.

**Comment by markpatton** [comment]
The Dspace REST API, https://github.com/DSpace/RestContract, is for version 7 and 8 and should also work for the upcoming 9. It is full featured and well documented. Using it seems straight-forward.

There is an older REST API which would allow for PASS deposit to versions 5 and 6, but it does not seem worth pursuing. See https://wiki.lyrasis.org/pages/viewpage.action?pageId=104566810. 

We can keep the sword deposit support around for older versions of DSpace until it introduces problems to the code base. At that point we can just drop it.
