### ISSUE TITLE
Real integration test for PubMed Central

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#616]
adding the work of discussing what funders we can support to this ticket, since it seems related. please use this spreadsheet to get information from contact at PMC so we can determine what new PASS can support: https://docs.google.com/spreadsheets/d/1JyOhYAnfwrH3NKMCovw55sPn-yMtMYG2fibOO-p_MFc/edit#gid=71450098

**Comment by dkriethof** [comment]
depends on deposit service and packages complete (1.0.0)

**Comment by tsande16** [comment]
@dkriethof @markpatton @rpoet-jh 

Updates from PMC:

- Will need to change the path that the files are upload to:
    - Currently we're FTPing the files to: /logs/upload/test/{todays_date}
    - They should be uploaded to: /upload/{todays_date}/
    - This directory applies to both their testing FTP server and production

- Need to change the compression of manuscripts from zip to zipped tar archive, e.g. `nihms-native-2017-07_2023-10-17_18-10-02_229717.tar.gz`
    - Attached is their full specification
[Bulk Submission Specs_Publishers_May 2022.pdf](https://github.com/eclipse-pass/main/files/13046568/Bulk.Submission.Specs_Publishers_May.2022.pdf)

- The list of funders is update-to-date here: https://www.ncbi.nlm.nih.gov/pmc/about/public-access/#partners
    - PASS should **NOT** support: DHS, NIST, or NASA
        - Because of DHS policy, only DHS funded papers can only be accepted by PubMed from DHS
        - NIST is similar to DHS
        - NASA no longer deposits manuscripts in PMC
       
- HHMI is still an active participant and PASS should still deposit to PMC for HHMI.

- Regarding the automation question: Automated emails are sent (in PROD) once submissions are detected and processed. We do not get automated emails in TEST, although I requested them to forward a few samples so we can see them. Notifications are sent out to the account that is setup for us in NIHMS (pass@jhu.edu). It is also the Submitter for all submissions. We are informed of the status of each submissions, whether it is successful or not.

**Comment by dkriethof** [comment]
Thank you!

________________________________

**Comment by tsande16** [comment]
Another follow-up email from PMC:

"Yes, we updated the DTD to streamline and clarify things a bit. While we do still support the old DTD, we recommend updating to the new one and hope that you will find it cleaner to use. We do not make updates to the DTD often, but we will keep you in the loop if we make any further updates.
 
E-mails about submissions that you make will be sent to the e-mail address(es) specified in the account set up for NIHMS, [dataconservancy@gmail.com](mailto:dataconservancy@gmail.com). This morning, I moved one of your test submissions to /upload/2023-10-23 and converted it to a .tar.gz file so our test system would pick it up and load it. I have attached the resulting status e-mail so you can see what they look like. This e-mail contains only one submission because I only loaded one of the test submissions, but if you were to upload multiple manuscripts, the e-mail would contain the statuses for each of submission loaded in that session.
 
Also, I missed responding to one of your previous questions regarding funder recognition. No, it is not possible to determine the funder by the journal. Rather, the Reviewer is required to associate the applicable funding as part of the initial review process. While PubMed may use additional metadata from the text acknowledgments in the paper itself, NIHMS can only recognize the funding that is explicitly associated by the Reviewer.
 
Please let me know if you have any further questions."

**Comment by tsande16** [comment]
Latest deposit to the test FTP server email notification:

![image](https://github.com/eclipse-pass/main/assets/100955095/1e2e3086-e429-4a5d-a573-a9db96087a3b)

**Comment by tsande16** [comment]
More tests submitted on Friday came back successful:



![Image](https://github.com/eclipse-pass/main/assets/100955095/364c81a7-0fb3-4cdc-806b-73c51e4e8bc9)
