### ISSUE TITLE
Identify a DSpace instance that staging can use for deposits

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#669]

**Comment by tsande16** [comment]
We currently have two instances in development:

- test / dev
- staging, pseudo-stable/prod-ready(ish)

Both are only accessible on the JHU network and requires the VPN. 

There are a couple options:

- Make the dspace instance public 
- Create a tunnel between our AWS Pass-staging and Dspace Staging

**Comment by tsande16** [comment]
Updates & Important things to note for the configuration:

Server: https://j10p-stage.library.jhu.edu/
Service Document: https://j10p-stage.library.jhu.edu/server/swordv2/servicedocument

In order to have the correct collection returning int he service document for the service account the following need to be done:

- Ensure that `swordv2-server.expose-communities = false` in the SWORDv2 server = ref [SWORDv2 Server](https://wiki.lyrasis.org/display/DSDOC7x/SWORDv2+Server)
- The service account is given specific permissions on the collection: JHU Open Access Research
    - https://j10p-stage.library.jhu.edu/collections/10e5df18-a5f6-40cd-aeea-fd562e318c19
    - Handle: [1774.2/58586](https://j10p-clone.library.jhu.edu/handle/1774.2/58586)
