### ISSUE TITLE
Add helpful text next to the Journal portion in the Basics step of the workflow

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#779]
This is a small update that will make the new "no journal required" workflow clearer for the user

**Comment by markpatton** [comment]
I think this is actually more confusing. It is just complicated. Consider a submission going to pmc, the user does not enter the journal because it says optional. A few steps later they are told a journal is required and to go back to the start where once again they are told the journal is optional.

Entering a journal is not optional in all circumstances. Whether or not a journal is optional is a property of a repository and we don't know anything about the repositories in this step.

Accurate text to put next to journal would be "optional for some repositories" or equivalently, "required for some repositories".  Instead it may make sense to add some explanatory text saying something like "Please enter journal information if possible. It is required for submission to some repositories."

**Comment by dkriethof** [comment]
Per the workflow itself, it is optional. More explanation is good, but leaving it w/ no explanation is confusing since a user with no journal won't know they can hit Next without submitting anything.

Whatever language you all choose to put in is fine, but there should be something helpful there to help both users who might require journals and users who do not have any journals.

**Comment by markpatton** [comment]
This discussion is showing how confusing it is! I still cannot agree that journal selection is optional. There is not enough information to make that statement at that step in the workflow. 

Should we get the working group to review all the text in the first step and then the warning when you get to the metadata step and are told you need to enter a journal?

**Comment by dkriethof** [comment]
Share w/ working group in Slack for feedback. Blocked for now.

**Comment by dkriethof** [comment]
Per discussions in Slack w/ the working group, adding helpful language next to the Journal step that notes seems to the consensus. Draft copy below.

"If you are an NIH-user, a journal selection is required to deposit into PMC. It is optional for all other users. If you do not see your journal listed, you can skip the journal selection and still use PASS to deposit into JScholarship.
