### ISSUE TITLE
Incorrect Data and Presentation of Submission on the Submissions Page

### ISSUE THREAD

**Issue by tsande16** [eclipse-pass/main#791]
Not sure if this is UI or backend, but tagged it as UI just in case.
Browser info: Firefox 118.0.2 (64-bit)

After two successful submissions and then viewing the submissions page, Tim Test10 is incorrectly displaying as a draft and there is a line that is missing an `Article` value. 

Checked the PMC FTP folder and there were two deposits there from these submissions (submissionId = 229852 and 229860):

nihms-native-2017-07_2023-10-20_20-10-09_229852.tar.gz 
nihms-native-2017-07_2023-10-20_20-10-39_229860.tar.gz

![image](https://github.com/eclipse-pass/main/assets/100955095/73f8ce10-28ce-4646-9d06-0241a06ef08b)

Links to the two tests, app & data per ID:

https://stage.pass.jhu.edu/app/submissions/229851
https://stage.pass.jhu.edu/data/submission/229851

https://stage.pass.jhu.edu/app/submissions/229852
https://stage.pass.jhu.edu/data/submission/229852

https://stage.pass.jhu.edu/app/submissions/229860
https://stage.pass.jhu.edu/data/submission/229860

Note: That is appears to have created two objects for Tim Test10 one that is a draft (229851) and submitted one to PMC (229852). 

The bulk XML submitted to PMC:
![image](https://github.com/eclipse-pass/main/assets/100955095/1ae37dc2-5a7d-4d49-87c0-6f18c440dac2)

**Comment by rpoet-jh** [comment]
Double click on the Submit button issue?

**Comment by tsande16** [comment]
@rpoet-jh I tried spamming the submit button, but didn't seem to occur again. Still haven't been able to reproduce the error.

**Comment by markpatton** [comment]
What submission is the one without a title?

**Comment by tsande16** [comment]
@markpatton It's https://stage.pass.jhu.edu/data/submission/229852

![image](https://github.com/eclipse-pass/main/assets/100955095/4ab43139-1e32-448e-a10d-5ffb7b2094fd)

**Comment by rpoet-jh** [comment]
I was able to get the UI to create two submissions (I can see it in the browser, two posts).  I don't see the blank submission in the Submissions table though.

In chrome inspector, turn on Throttling Slow 3G on the Network tab.  Then Create a new submission.  Fill fields out on first page, then double click the Next button.  You will see two posts to the submission api.  The state of wizard gets weird after that.  I'm not sure if this exactly what happened in 791, but it does seem like we need to disable the Next button on click since it is posting to the api (for all Next buttons that create data).
