### ISSUE TITLE
A few grants in assets image has internal uris on their funder fields

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#82]
![screen shot 2018-11-26 at 11 47 21 am](https://user-images.githubusercontent.com/11050142/49028792-37871c00-f171-11e8-8d6b-2ebbc2cf4e88.png)

Ember can't handle these `http://fcrepo:8080/fcrepo/` prefixed uris and displays error popup up

Update Assets image to fix the data correct the uris
Investigate the cause of the issue to make sure more bad data doesn't get in.

**Comment by karenhanson** [comment]
I have replicated this in current `assets` image. Note that these records look fine in elasticsearch because of the way elasticsearch treat Fedora URIs. To see the effect you need to visit the link in this format, i.e. not using `http://fcrepo:8080`:
http://pass.local:8080/fcrepo/rest/grants/98/b0/73/70/98b07370-c51d-4745-a6bf-81f058c02587
http://localhost:8080/fcrepo/rest/grants/98/b0/73/70/98b07370-c51d-4745-a6bf-81f058c02587

You will see that the ID URI is different from pi, primaryFunder, directFunder.

**Comment by markpatton** [comment]
No longer relevant.
