### ISSUE TITLE
Create csv template for grant ingestion

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#844]
Create the example CSV with fields necessary for PASS to ingest grant data to share w/ institutions

**Comment by rpoet-jh** [comment]
The table below contains all the columns that would be required in a CSV file to use for importing grant/funder/user (PI) data into PASS.

Notes:

- If there is more than one PI on a grant (Co-PIs), the row should be duplicated except for the PI fields which would contain the additional PI data.
- In order to process the CSV, the funder to policy mapping would need to be created and be in place in the PASS system.
- _There is no code currently in grant loader that supports processing data in this CSV format.  This requires a code change to add support for CSV import._

Column | Type/Size | Required | Description
-- | -- | -- | --
GRANT_NUMBER | TEXT/255 | Y | Unique identifier for the grant  (institutional Grant ID)
GRANT_TITLE | TEXT/255 | Y | The title of the grant
AWARD_NUMBER | TEXT/255 | Y | Unique identifier for the award
AWARD_STATUS | TEXT/255 | Y | The status of the award.Valid values: active, pre-award, terminated
AWARD_DATE | DATE | Y | The date the grant award was createdFormat: MM/DD/YYYY
AWARD_START | TIMESTAMP | Y | The timestamp the grant award beginsFormat: YYYY-MM-DD HH:MM:SS.SSS
AWARD_END | TIMESTAMP | Y | The timestamp the grant award endsFormat: YYYY-MM-DD HH:MM:SS.SSS
PRIMARY_FUNDER_NAME | TEXT/255 | Y | The Primary Funder Name (Funder of original source of funds)
PRIMARY_FUNDER_CODE | TEXT/255 | Y | The Primary Funder unique identifier (institutional Funder ID)
DIRECT_FUNDER_NAME | TEXT/255 | Y | The Direct Funder Name (Funder from which funds are directly received)
DIRECT_FUNDER_CODE | TEXT/255 | Y | The Direct Funder unique identifier  (institutional Funder ID)
PI_FIRST_NAME | TEXT/255 | Y | First name of PI
PI_MIDDLE_NAME | TEXT/255 | N | Middle name of PI
PI_LAST_NAME | TEXT/255 | Y | Last name of PI
PI_EMAIL | TEXT/255 | Y | Email address of PI
PI_INSTITUTIONAL_ID | TEXT/128 | Y | Institutional User ID of PI (for example, for JHU, this is the jhedId)
PI_EMPLOYEE_ID | TEXT/128 | Y | Employee ID of PI
PI_ROLE | TEXT/1 | Y | Role of PI on grant (PI or Co-PI)Valid values: P, CP = PI, C = Co-PI
UPDATE_TIMESTAMP | TIMESTAMP | N | Last update timestampFormat: YYYY-MM-DD HH:MM:SS.SSS

**Comment by dkriethof** [comment]
re: "This requires a code change to add support for CSV import," - yep, was planning to create some follow-up tickets once we have this template confirmed.

**Comment by markpatton** [comment]
This makes sense. Looks good.

**Comment by bbranan** [comment]
If we create a lookup table of funders by ID, then PRIMARY_FUNDER_NAME and DIRECT_FUNDER_NAME could become optional (or not included at all). Another benefit of this is that those funder names would be standardized rather than all possible permutations of a name.

**Comment by rpoet-jh** [comment]
@bbranan `If we create a lookup table of funders by ID/code, then PRIMARY_FUNDER_NAME and DIRECT_FUNDER_NAME could become optional (or not included at all). Another benefit of this is that those funder names would be standardized rather than all possible permutations of a name.`

This is a possible normalization of the data import, but it would impact grant loader quite a bit.  Grant loader logic creates/updates funder data based on the grant record as proposed.  If we want to extract funder data into a separate reference data structure, we would have to extend grant loader to load a funder data from a file with a different format, then generate the grant data csv file with the IDs and run another import for grant data ingestion.

I think keeping the grant/funder/pi data flattened out as specified keeps the import more straightforward with less steps needed to ingest data.  Yes, it is not as normalized, but I think doing the initial import and updates with one file format is easier to deal with.

This being said, let me know if you want to talk about this more.

**Comment by bbranan** [comment]
No need to pursue this normalization at the moment. I was calling it out as a potential way to reduce the number of required fields, for the benefit of other institutions. Let's see what type of feedback we receive before attempting any optimization.
