### ISSUE TITLE
PASS production reported a call to the schema service without being passed any repository ids

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#876]
# What? 

The problem shows up as two metadata schema service requests without the entityIds parameter. The requests fail and show up as errors in the logs.

I managed to recreate this once by starting a submission, going through to the metadata step, going back to the dashboard, going to submissions, clicking on delete for that draft submission and then clicking on the submission.

But of the three times I tried, the bug only happened once.

# Why?

This is a minor bug that should be fixed.

# How?

The schema service is only called by setupSchemas in app/components/workflow-metadata/index.js. For some reason it is getting called in this situation.

# Acceptance Criteria 

The problem doesn't occur when doing the above test.

# Related Issues

**Comment by jabrah** [comment]
I have not been able to reproduce following those steps, but It might be worth making the part of the UI that calls the schema service a bit more defensive to not issue the request when it finds no entityIds

**Comment by markpatton** [comment]
@jabrah That makes sense.

**Comment by jabrah** [comment]
I believe this was caused by some odd behavior from Ember: when using the service from the Submission Details page, the arguments passed to the service would be Proxy objects, instead of the expected array of strings. `ObjectProxy.toArray()` before passing the arg into the service seems to work alright in tests

I've also made it so that no or empty args passed to the service don't make REST requests to the schema-service
