### ISSUE TITLE
Created automated tests that can  be run against a PASS environment

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#909]
# What? 

Create automated tests that can be run against the different PASS environments.

There should be a set of read only tests for the production environment.

The write tests should include at the least deposit to JScholarship. The write tests should clean up after themselves to the extent possible. Need to make sure they won't negatively impact staging.

# Why?

Automated testing will help give us confidence about code testing.

# How?

Attempt to update pass-existing-testing to do end to end tests.

# Acceptance Criteria 

What must be true for this work to be considered complete and correct? Include if applicable.

# Related Issues

**Comment by rpoet-jh** [comment]
Here are my initial thoughts:

**Authentication**

Authentication for the e2e tests (pass-acceptance-tests) in the live environment is probably the trickiest automation part of this because of JHU SSO login.  Here are a few proposals that I can think of:

- Create a new authentication scheme that would only be used by e2e tests.  A new URL path with a query param or cookie containing a token for authentication (maybe JWT).  The token would be generated for each user.  A new security filter would detect this request and handle authentication using the token.  We could also add a switch in the app to enable and disable this authentication scheme so it would only be active while running e2e tests.
- Create test users in JHU IDP.  See if there is a way to get the 2FA requirement disabled for these user accounts so tests can just do simple login.
- Create test users in JHU IDP.  Setup 2FA and get key and use approach https://medium.com/@udarasembukuttiarachchi/can-we-automate-a-login-with-two-factor-authentication-1eb28ee5d729

If you have another idea, please comment.

**Test Data**

- One time test reference data insertion:
	- Create a test grant.  It can be associated with real funder/policy.  Test will only be for jscholarship policy.  We don't want nihms deposits happening as part of these tests.
	- Create test users and put them on the test grant

- Clean up data after tests:
	- We would ideally want to run our existing e2e tests that do read and write operations.  Therefore, we have to clean up any submission and deposit related data related to tests.
	- Before the test suite runs, a script would run to delete all submission and deposit related data associated to the test grant
		- By running this before the test, in cases where there are test failures, it will make it possible to see the data for analysis
	- Run a nightly job to clean all submission and deposit related data associated to the test grant to ensure test data is cleaned within 24 hours

**Test Execution**

- The pass-acceptance-tests would be updated to run tests against an actual PASS environment (i.e. the domain in browser would be stage.pass.jhu.edu and app.pass.jhu.edu)
- In the JHU deployment workflows:
	- When a Pass App deployment runs, we will also run pass-acceptance-tests
		- The clean up test data script will run as part of this job too
	- If the tests fail, the deployment will be marked as failed
	- Future, when we have blue green deployments, this same setup of running the pass-acceptance-tests will be used, except the tests will run against the Green environment before the switch happens

**Comment by rpoet-jh** [comment]
Couple more things related to first authentication approach of using JWT:

- Spring security example of providing a way to get and authenticate with JWT: https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/jwt/login
- We could setup a script to add the github action runner IP to a security group on the public LB for getting /token, and block every other IP address.  So only our e2e tests would be using the JWT authentication.
- With this, we can add a new login script in the e2e tests to get a token for each test user and use it as a Bearer token.  Then when the tests are done, we would remove the github running IP from the aws sec group on the alb.

**Comment by rpoet-jh** [comment]
Note about second authentication approach, "Create test users in JHU IDP. See if there is a way to get the 2FA requirement disabled for these user accounts so tests can just do simple login.".

I checked with Jeff, and it does sound possible to create a service user account that we could use for our acceptance testing against deployed PASS.  For example, we would have `pass-test-staff@jh.edu` created that we would login to PASS and execute tests.

I'm still analyzing, but this seems like the option that would require the least amount of change in pass-core.

**Comment by jabrah** [comment]
To clarify, would we still be maintaining the current tests that run against the `pass-docker` environment on PRs and adding these deployment tests or would this be removing the on-PR tests in favor of the deployment tests?

**Comment by rpoet-jh** [comment]
@jabrah We would be adding to pass-acceptance-tests for the deployment tests.  The current acceptance tests that run against `pass-docker` on PRs would remain.  The tests may be slightly refactored for reuse, but the running of the acceptance tests against pass-docker on PRs would stay the same.
