### ISSUE TITLE
Review and add sample grant CSV (from CalTech) to PASS to share via local machine

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#928]
What?
Add CalTech sample grant data to PASS on dev local machine to share in demo.

Notes from from CalTech:
"...attached our grant export reformatted in the structure expected by PASS. I excluded a number of sub-awards where we don’t have a mapping between the funder and funder identifier. Our export doesn’t include PI IDs or emails, so we don’t have a way of mapping between grants and a PI institutional login at the moment. **Our use case probably will involve making all the grants available to an admin account, so just assigning everything to a single account will probably be fine for testing purposes.**"

Why?
We want as much sample data from our community institutions as possible to see how the simple grant data loader will work. Would like to be able to share PASS demo w/ group in Feb 28 meeting.

How?

Reference
[Link to data](https://drive.google.com/file/d/1xjDSpmCt9dmjl8svOOddQESPqPBIF49x/view?usp=sharing
)

Related tickets
n/a

**Comment by rpoet-jh** [comment]
As a note, none of the records in the linked CSV will import into PASS because there must be a PI_EMPLOYEE_ID or PI_INSTITUTIONAL_ID value for the grant ingest record to import (also PI_EMAIL is required, but that is something else).  Second, not sure if this is expected, but it appears they sent their entire grant database instead of a sample (~7600 records).

**Comment by dkriethof** [comment]
Closing since we an't import this data.
